# Site settings
author: Jake Garcia
title: Jake = Developer.new
header-img: img/home-bg.png
email: bballwiz4@gmail.com
copyright_name: Jake Garcia
description: > # this means to ignore newlines until "baseurl:"
  Continue to Learn and Grow
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jgarcia4444

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
